name: Build ProspectTogether

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true  # fetch Foundation

    - name: Setup Build Dependencies
      run: |
        $vs_version = $(Get-Content .\modinfo.json | jq -r .dependencies.game)
        $filename = "vs_server_linux-x64_${vs_version}.zip"
        $folder = if ($vs_version -like "*-rc*") { "unstable" } else { "stable" }
        $uri = "https://cdn.vintagestory.at/gamefiles/${folder}/${filename}"
        Invoke-WebRequest -Uri $uri -Out $filename
        $vsdir = $(mkdir VintageStory)
        cd VintageStory
        tar -zxvf "..\$filename" Lib/ Mods/ VintagestoryAPI.dll
        Add-Content -Path $Env:GITHUB_ENV -Value "VINTAGE_STORY=${vsdir.FullPath}"
      shell: pwsh

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Restore Mod Dependencies
      run: msbuild /t:Restore /p:Configuration=Release

    - name: Build Mod
      run: msbuild /t:Build /p:Configuration=Release
      env:
        VINTAGE_STORY: ${{ env.VINTAGE_STORY }}

    - name: Finalize Artifact
      run: |
        $mod_name = $(Get-Content .\modinfo.json | jq -r .name)
        $mod_version = $(Get-Content .\modinfo.json | jq -r .version)
        Add-Content -Path $Env:GITHUB_ENV -Value "ARTIFACT_NAME=${mod_name}-${mod_version}"
        Remove-Item ./bin/Release/net7/VintagestoryAPI.dll  # not sure why this makes it through the filter?
      shell: pwsh

    - name: Upload Mod Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ./bin/Release/net7/


